export const AttendanceService = {
  getData() {
    return [
      {
        date: "01-01-2022",
        department: "IT",
        designation: "Front-end",
        checkin: "9:00 AM",
        checkout: "6:00 PM",
        workinghours: "9 HOURS",
        shift: "Morning",
        status: "Present",
        action: "Edit",
        balance: 500,
        id: 1,
        image:"https://i.pinimg.com/474x/5d/69/42/5d6942c6dff12bd3f960eb30c5fdd0f9.jpg", // Replace with actual image URL
        name: "George",
        firstIn: "08:00 AM",
        break: "45 mins",
        lastOut: "05:00 PM",
        total: "7 hrs",
        attendance: {
          "day1": "✔️",
          "day2": "✔️",
          "day3": "✔️",
          "day4": "✔️",
          "day5": "✔️",
          "day6": "✔️",
          "day7": "✔️",
          "day8": "✔️",
          "day9": "✔️",
          "day10": "✔️",
          "day11": "✔️",
          "day12": "✔️",
          "day13": "❌",
          "day14": "✔️",
          "day15": "✔️",
          "day16": "✔️",
          "day17": "✔️",
          "day18": "⭐",
          "day19": "✔️",
          "day20": "✔️",
          "day21": "✔️",
          "day22": "✔️",
          "day23": "✔️",
          "day24": "✔️",
          "day25": "✔️",
          "day26": "✔️",
          "day27": "✔️",
          "day28": "✔️",
          "day29": "✔️",
          "day30": "✔️",
        }
        
      },
      {
        date: "01-02-2022",
        department: "IT",
        designation: "Back-end",
        checkin: "9:30 AM",
        checkout: "6:30 PM",
        workinghours: "9 HOURS",
        shift: "Morning",
        status: "Present",
        action: "Edit",
        balance: 550,
        id: 2,
        image:
          "https://i.pinimg.com/474x/5d/69/42/5d6942c6dff12bd3f960eb30c5fdd0f9.jpg", // Replace with actual image URL
        name: "Thomas",
        firstIn: "08:15 AM",
        break: "30 mins",
        lastOut: "05:30 PM",
        total: "8 hrs",
        attendance: {
          "day1": "✔️",
          "day2": "✔️",
          "day3": "✔️",
          "day4": "✔️",
          "day5": "✔️",
          "day6": "✔️",
          "day7": "✔️",
          "day8": "✔️",
          "day9": "✔️",
          "day10": "✔️",
          "day11": "✔️",
          "day12": "✔️",
          "day13": "✔️",
          "day14": "✔️",
          "day15": "✔️",
          "day16": "✔️",
          "day17": "✔️",
          "day18": "✔️",
          "day19": "✔️",
          "day20": "✔️",
          "day21": "✔️",
          "day22": "✔️",
          "day23": "✔️",
          "day24": "✔️",
          "day25": "❌",
          "day26": "✔️",
          "day27": "✔️",
          "day28": "⭐",
          "day29": "✔️",
          "day30": "✔️",
        }
      },
      {
        id: 3,
        image:
          "https://i.pinimg.com/474x/5d/69/42/5d6942c6dff12bd3f960eb30c5fdd0f9.jpg", // Replace with actual image URL
        name: "Riya",
        firstIn: "09:00 AM",
        break: "60 mins",
        lastOut: "06:00 PM",
        total: "8 hrs",
        status: "Active",
        shift: "Morning",
        date: "01-03-2022",
        department: "IT",
        designation: "Designer",
        checkin: "10:00 AM",
        checkout: "7:00 PM",
        workinghours: "9 HOURS",
        action: "Edit",
        balance: 600,
        attendance: {
          "day1": "✔️",
          "day2": "✔️",
          "day3": "✔️",
          "day4": "✔️",
          "day5": "✔️",
          "day6": "✔️",
          "day7": "✔️",
          "day8": "✔️",
          "day9": "✔️",
          "day10": "✔️",
          "day11": "✔️",
          "day12": "✔️",
          "day13": "✔️",
          "day14": "✔️",
          "day15": "✔️",
          "day16": "✔️",
          "day17": "✔️",
          "day18": "✔️",
          "day19": "✔️",
          "day20": "✔️",
          "day21": "✔️",
          "day22": "✔️",
          "day23": "✔️",
          "day24": "✔️",
          "day25": "✔️",
          "day26": "✔️",
          "day27": "⭐",
          "day28": "✔️",
          "day29": "✔️",
          "day30": "❌",
        }
      },
      {
        id: 4,
        image:
          "https://i.pinimg.com/474x/5d/69/42/5d6942c6dff12bd3f960eb30c5fdd0f9.jpg", // Replace with actual image URL
        name: "Willams",
        firstIn: "08:30 AM",
        break: "45 mins",
        lastOut: "05:30 PM",
        total: "8 hrs",
        date: "01-04-2022",
        department: "IT",
        designation: "Testing",
        checkin: "9:15 AM",
        checkout: "6:15 PM",
        workinghours: "9 HOURS",
        shift: "Morning",
        status: "Present",
        action: "Edit",
        balance: 520,
        attendance: {
          "day1": "✔️",
          "day2": "✔️",
          "day3": "✔️",
          "day4": "✔️",
          "day5": "✔️",
          "day6": "✔️",
          "day7": "✔️",
          "day8": "✔️",
          "day9": "✔️",
          "day10": "✔️",
          "day11": "✔️",
          "day12": "✔️",
          "day13": "✔️",
          "day14": "⭐",
          "day15": "✔️",
          "day16": "✔️",
          "day17": "✔️",
          "day18": "✔️",
          "day19": "✔️",
          "day20": "✔️",
          "day21": "✔️",
          "day22": "✔️",
          "day23": "✔️",
          "day24": "✔️",
          "day25": "❌",
          "day26": "✔️",
          "day27": "✔️",
          "day28": "✔️",
          "day29": "✔️",
          "day30": "✔️",
        }
      },
      {
        id: 5,
        image:
          "https://i.pinimg.com/474x/5d/69/42/5d6942c6dff12bd3f960eb30c5fdd0f9.jpg", // Replace with actual image URL
        name: "Joseph",
        firstIn: "09:15 AM",
        break: "30 mins",
        lastOut: "06:15 PM",
        total: "8 hrs",
        date: "01-05-2022",
        department: "IT",
        designation: "Designer",
        checkin: "9:45 AM",
        checkout: "6:45 PM",
        workinghours: "9 HOURS",
        shift: "Morning",
        status: "Present",
        action: "Edit",
        balance: 560,
        attendance: {
          "day1": "✔️",
          "day2": "✔️",
          "day3": "✔️",
          "day4": "✔️",
          "day5": "✔️",
          "day6": "✔️",
          "day7": "✔️",
          "day8": "✔️",
          "day9": "✔️",
          "day10": "✔️",
          "day11": "✔️",
          "day12": "✔️",
          "day13": "✔️",
          "day14": "❌",
          "day15": "✔️",
          "day16": "✔️",
          "day17": "✔️",
          "day18": "✔️",
          "day19": "✔️",
          "day20": "⭐",
          "day21": "✔️",
          "day22": "✔️",
          "day23": "✔️",
          "day24": "✔️",
          "day25": "✔️",
          "day26": "✔️",
          "day27": "✔️",
          "day28": "✔️",
          "day29": "✔️",
          "day30": "✔️",
        }
      },
      {
        id: 6,
        image:
          "https://i.pinimg.com/474x/5d/69/42/5d6942c6dff12bd3f960eb30c5fdd0f9.jpg", // Replace with actual image URL
        name: "John",
        firstIn: "09:30 AM",
        break: "45 mins",
        lastOut: "06:30 PM",
        total: "8 hrs",
        date: "01-06-2022",
        department: "IT",
        designation: "Testing",
        checkin: "9:30 AM",
        checkout: "6:30 PM",
        workinghours: "9 HOURS",
        shift: "Morning",
        status: "Absent",
        action: "Edit",
        balance: 610,
        attendance: {
          "day1": "✔️",
          "day2": "✔️",
          "day3": "✔️",
          "day4": "✔️",
          "day5": "✔️",
          "day6": "✔️",
          "day7": "✔️",
          "day8": "✔️",
          "day9": "✔️",
          "day10": "✔️",
          "day11": "✔️",
          "day12": "✔️",
          "day13": "✔️",
          "day14": "✔️",
          "day15": "✔️",
          "day16": "✔️",
          "day17": "✔️",
          "day18": "✔️",
          "day19": "✔️",
          "day20": "✔️",
          "day21": "❌",
          "day22": "✔️",
          "day23": "✔️",
          "day24": "✔️",
          "day25": "✔️",
          "day26": "⭐",
          "day27": "✔️",
          "day28": "✔️",
          "day29": "✔️",
          "day30": "✔️",
        }
      },
      {
        id: 7,
        image:
          "https://i.pinimg.com/474x/5d/69/42/5d6942c6dff12bd3f960eb30c5fdd0f9.jpg", // Replace with actual image URL
        name: "Richard",
        firstIn: "08:45 AM",
        break: "30 mins",
        lastOut: "05:45 PM",
        total: "8 hrs",
        date: "01-07-2022",
        department: "IT",
        designation: "Front-end",
        checkin: "9:00 AM",
        checkout: "6:00 PM",
        workinghours: "9 HOURS",
        shift: "Morning",
        status: "Present",
        action: "Edit",
        balance: 540,
        attendance: {
          "day1": "✔️",
          "day2": "✔️",
          "day3": "✔️",
          "day4": "✔️",
          "day5": "✔️",
          "day6": "✔️",
          "day7": "✔️",
          "day8": "✔️",
          "day9": "✔️",
          "day10": "✔️",
          "day11": "✔️",
          "day12": "✔️",
          "day13": "⭐",
          "day14": "✔️",
          "day15": "✔️",
          "day16": "✔️",
          "day17": "✔️",
          "day18": "✔️",
          "day19": "✔️",
          "day20": "✔️",
          "day21": "✔️",
          "day22": "✔️",
          "day23": "✔️",
          "day24": "❌",
          "day25": "✔️",
          "day26": "✔️",
          "day27": "✔️",
          "day28": "✔️",
          "day29": "✔️",
          "day30": "✔️",
        }
      },
      {
        id: 8,
        image:
          "https://i.pinimg.com/474x/5d/69/42/5d6942c6dff12bd3f960eb30c5fdd0f9.jpg", // Replace with actual image URL
        name: "Maya",
        firstIn: "09:45 AM",
        break: "60 mins",
        lastOut: "06:45 PM",
        total: "8 hrs",
        date: "01-08-2022",
        department: "IT",
        designation: "Back-end",
        checkin: "9:15 AM",
        checkout: "6:15 PM",
        workinghours: "9 HOURS",
        shift: "Morning",
        status: "Present",
        action: "Edit",
        balance: 580,
        attendance: {
          "day1": "✔️",
          "day2": "✔️",
          "day3": "✔️",
          "day4": "✔️",
          "day5": "✔️",
          "day6": "✔️",
          "day7": "✔️",
          "day8": "✔️",
          "day9": "✔️",
          "day10": "✔️",
          "day11": "✔️",
          "day12": "✔️",
          "day13": "✔️",
          "day14": "✔️",
          "day15": "✔️",
          "day16": "✔️",
          "day17": "✔️",
          "day18": "✔️",
          "day19": "✔️",
          "day20": "⭐",
          "day21": "✔️",
          "day22": "✔️",
          "day23": "✔️",
          "day24": "❌",
          "day25": "✔️",
          "day26": "✔️",
          "day27": "✔️",
          "day28": "✔️",
          "day29": "✔️",
          "day30": "✔️",
        }
      },
      {
        id: 9,
        image:
          "https://i.pinimg.com/474x/5d/69/42/5d6942c6dff12bd3f960eb30c5fdd0f9.jpg", // Replace with actual image URL
        name: "Davidson",
        firstIn: "08:15 AM",
        break: "45 mins",
        lastOut: "05:15 PM",
        total: "7.5 hrs",
        date: "01-09-2022",
        department: "IT",
        designation: "Testing",
        checkin: "9:30 AM",
        checkout: "6:30 PM",
        workinghours: "9 HOURS",
        shift: "Morning",
        status: "Absent",
        action: "Edit",
        balance: 620,
        attendance: {
          "day1": "✔️",
          "day2": "✔️",
          "day3": "✔️",
          "day4": "✔️",
          "day5": "✔️",
          "day6": "✔️",
          "day7": "✔️",
          "day8": "✔️",
          "day9": "✔️",
          "day10": "✔️",
          "day11": "✔️",
          "day12": "✔️",
          "day13": "✔️",
          "day14": "❌",
          "day15": "✔️",
          "day16": "✔️",
          "day17": "✔️",
          "day18": "✔️",
          "day19": "✔️",
          "day20": "⭐",
          "day21": "✔️",
          "day22": "✔️",
          "day23": "✔️",
          "day24": "✔️",
          "day25": "✔️",
          "day26": "✔️",
          "day27": "✔️",
          "day28": "✔️",
          "day29": "✔️",
          "day30": "✔️",
        }
      },

      {
        id: 10,
        image:
          "https://i.pinimg.com/474x/5d/69/42/5d6942c6dff12bd3f960eb30c5fdd0f9.jpg", // Replace with actual image URL
        name: "Jasmine",
        firstIn: "08:30 AM",
        break: "30 mins",
        lastOut: "05:30 PM",
        total: "8 hrs",
        date: "01-10-2022",
        department: "IT",
        designation: "Testing",
        checkin: "9:45 AM",
        checkout: "6:45 PM",
        workinghours: "9 HOURS",
        shift: "Morning",
        status: "Present",
        action: "Edit",
        balance: 550,
        attendance: {
          "day1": "✔️",
          "day2": "✔️",
          "day3": "✔️",
          "day4": "✔️",
          "day5": "✔️",
          "day6": "✔️",
          "day7": "✔️",
          "day8": "✔️",
          "day9": "✔️",
          "day10": "✔️",
          "day11": "✔️",
          "day12": "✔️",
          "day13": "✔️",
          "day14": "✔️",
          "day15": "❌",
          "day16": "✔️",
          "day17": "✔️",
          "day18": "✔️",
          "day19": "✔️",
          "day20": "⭐",
          "day21": "✔️",
          "day22": "✔️",
          "day23": "✔️",
          "day24": "✔️",
          "day25": "✔️",
          "day26": "✔️",
          "day27": "✔️",
          "day28": "✔️",
          "day29": "✔️",
          "day30": "✔️",
        }
      },
      {
        id: 11,
        image:
          "https://i.pinimg.com/474x/5d/69/42/5d6942c6dff12bd3f960eb30c5fdd0f9.jpg", // Replace with actual image URL
        name: "Rohit",
        firstIn: "09:00 AM",
        break: "45 mins",
        lastOut: "06:00 PM",
        total: "8 hrs",
        date: "01-11-2022",
        department: "IT",
        designation: "Front-end",
        checkin: "10:00 AM",
        checkout: "7:00 PM",
        workinghours: "9 HOURS",
        shift: "Morning",
        status: "Present",
        action: "Edit",
        balance: 590,
        attendance: {
          "day1": "✔️",
          "day2": "✔️",
          "day3": "✔️",
          "day4": "✔️",
          "day5": "✔️",
          "day6": "✔️",
          "day7": "✔️",
          "day8": "⭐",
          "day9": "✔️",
          "day10": "✔️",
          "day11": "✔️",
          "day12": "✔️",
          "day13": "✔️",
          "day14": "❌",
          "day15": "✔️",
          "day16": "✔️",
          "day17": "✔️",
          "day18": "✔️",
          "day19": "✔️",
          "day20": "✔️",
          "day21": "✔️",
          "day22": "✔️",
          "day23": "✔️",
          "day24": "✔️",
          "day25": "✔️",
          "day26": "✔️",
          "day27": "✔️",
          "day28": "✔️",
          "day29": "✔️",
          "day30": "✔️",
        }
      },
      {
        id: 12,
        image:
          "https://i.pinimg.com/474x/5d/69/42/5d6942c6dff12bd3f960eb30c5fdd0f9.jpg", // Replace with actual image URL
        name: "Micheal",
        firstIn: "09:15 AM",
        break: "30 mins",
        lastOut: "06:15 PM",
        total: "8 hrs",
        date: "01-12-2022",
        department: "IT",
        designation: "Back-end",
        checkin: "9:15 AM",
        checkout: "6:15 PM",
        workinghours: "9 HOURS",
        shift: "Morning",
        status: "Absent",
        action: "Edit",
        balance: 630,
        attendance: {
          "day1": "✔️",
          "day2": "✔️",
          "day3": "✔️",
          "day4": "✔️",
          "day5": "✔️",
          "day6": "✔️",
          "day7": "✔️",
          "day8": "✔️",
          "day9": "✔️",
          "day10": "✔️",
          "day11": "✔️",
          "day12": "⭐",
          "day13": "✔️",
          "day14": "✔️",
          "day15": "✔️",
          "day16": "✔️",
          "day17": "✔️",
          "day18": "✔️",
          "day19": "❌",
          "day20": "✔️",
          "day21": "✔️",
          "day22": "✔️",
          "day23": "✔️",
          "day24": "✔️",
          "day25": "✔️",
          "day26": "✔️",
          "day27": "✔️",
          "day28": "✔️",
          "day29": "✔️",
          "day30": "✔️",
        }
      },
      {
        id: 13,
        image:
          "https://i.pinimg.com/474x/5d/69/42/5d6942c6dff12bd3f960eb30c5fdd0f9.jpg", // Replace with actual image URL
        name: "kingston",
        firstIn: "09:30 AM",
        break: "45 mins",
        lastOut: "06:30 PM",
        total: "8 hrs",
        date: "01-13-2022",
        department: "IT",
        designation: "Back-end",
        checkin: "9:30 AM",
        checkout: "6:30 PM",
        workinghours: "9 HOURS",
        shift: "Morning",
        status: "Present",
        action: "Edit",
        balance: 560,
        attendance: {
          "day1": "✔️",
          "day2": "✔️",
          "day3": "✔️",
          "day4": "✔️",
          "day5": "✔️",
          "day6": "✔️",
          "day7": "✔️",
          "day8": "✔️",
          "day9": "✔️",
          "day10": "✔️",
          "day11": "⭐",
          "day12": "✔️",
          "day13": "✔️",
          "day14": "✔️",
          "day15": "✔️",
          "day16": "✔️",
          "day17": "✔️",
          "day18": "✔️",
          "day19": "✔️",
          "day20": "✔️",
          "day21": "✔️",
          "day22": "✔️",
          "day23": "❌",
          "day24": "✔️",
          "day25": "✔️",
          "day26": "✔️",
          "day27": "✔️",
          "day28": "✔️",
          "day29": "✔️",
          "day30": "✔️",
        }
      },
      {
        id: 14,
        image:
          "https://i.pinimg.com/474x/5d/69/42/5d6942c6dff12bd3f960eb30c5fdd0f9.jpg", // Replace with actual image URL
        name: "Rakesh",
        firstIn: "08:00 AM",
        break: "45 mins",
        lastOut: "05:00 PM",
        total: "7 hrs",
        date: "01-14-2022",
        department: "IT",
        designation: "Testing",
        checkin: "9:45 AM",
        checkout: "6:45 PM",
        workinghours: "9 HOURS",
        shift: "Morning",
        status: "Present",
        action: "Edit",
        balance: 600,
        attendance: {
          "day1": "✔️",
          "day2": "✔️",
          "day3": "✔️",
          "day4": "✔️",
          "day5": "✔️",
          "day6": "⭐",
          "day7": "✔️",
          "day8": "✔️",
          "day9": "✔️",
          "day10": "✔️",
          "day11": "✔️",
          "day12": "✔️",
          "day13": "❌",
          "day14": "✔️",
          "day15": "✔️",
          "day16": "✔️",
          "day17": "✔️",
          "day18": "✔️",
          "day19": "✔️",
          "day20": "✔️",
          "day21": "✔️",
          "day22": "✔️",
          "day23": "✔️",
          "day24": "✔️",
          "day25": "✔️",
          "day26": "✔️",
          "day27": "✔️",
          "day28": "✔️",
          "day29": "✔️",
          "day30": "✔️",
        }
      },
      {
        id: 15,
        image:
          "https://i.pinimg.com/474x/5d/69/42/5d6942c6dff12bd3f960eb30c5fdd0f9.jpg", // Replace with actual image URL
        name: "Stanley",
        firstIn: "08:15 AM",
        break: "30 mins",
        lastOut: "05:30 PM",
        total: "8 hrs",
        date: "01-15-2022",
        department: "IT",
        designation: "Front-end",
        checkin: "10:00 AM",
        checkout: "7:00 PM",
        workinghours: "9 HOURS",
        shift: "Morning",
        status: "Absent",
        action: "Edit",
        balance: 640,
        attendance: {
          "day1": "✔️",
          "day2": "✔️",
          "day3": "✔️",
          "day4": "✔️",
          "day5": "✔️",
          "day6": "✔️",
          "day7": "✔️",
          "day8": "✔️",
          "day9": "✔️",
          "day10": "✔️",
          "day11": "✔️",
          "day12": "✔️",
          "day13": "✔️",
          "day14": "❌",
          "day15": "✔️",
          "day16": "✔️",
          "day17": "✔️",
          "day18": "✔️",
          "day19": "✔️",
          "day20": "⭐",
          "day21": "✔️",
          "day22": "✔️",
          "day23": "✔️",
          "day24": "✔️",
          "day25": "✔️",
          "day26": "✔️",
          "day27": "✔️",
          "day28": "✔️",
          "day29": "✔️",
          "day30": "✔️",
        }
      },
    ];
  },

  getCustomersSmall() {
    return Promise.resolve(this.getData().slice(0, 10));
  },

  getCustomersMedium() {
    return Promise.resolve(this.getData().slice(0, 50));
  },

  getCustomersLarge() {
    return Promise.resolve(this.getData().slice(0, 200));
  },

  getCustomersXLarge() {
    return Promise.resolve(this.getData());
  },

  getCustomers(params) {
    const queryParams = params
      ? Object.keys(params)
          .map(
            (k) => encodeURIComponent(k) + "=" + encodeURIComponent(params[k])
          )
          .join("&")
      : "";

    return fetch(
      "https://www.primefaces.org/data/customers?" + queryParams
    ).then((res) => res.json());
  },
};
